### PR TITLE
Add force set direction generic script

### PR DESCRIPTION
**Pull request by Garume**
I'm thinking of making a DSR scripts.
Could use it for that.

### CODE REVIEW

**Comment by Limiana** [comment]
Hey!
Did you check that it:
- Actually reflects your position server-side (ask a friend/use 2nd account to see if upon script activation you are indeed facing position you desire)
- It doesn't spams server with rotate requests?

Don't worry if you didn't - I can run both tests myself

**Comment by Garume** [comment]
Hi,
I hadn't thought about that at all!
As for the first point, it does function correctly from another person's perspective.
As for the second point, given that the first one is confirmed, there's a high possibility that it's spamming the server. (I haven't been able to test this yet.)
As a countermeasure, would calling AutoFaceTargetPosition every few milliseconds work?
Or perhaps, should I close it?

**Comment by Garume** [comment]
Changes.
- To be executed every 50ms.
- Added a setting that only works when the player is standing still
- Fixed a bug related to angles

**Comment by Limiana** [comment]
Thank you!
If you use it in scripts, options like that should be disabled by default

**Pull request merged**
